package telas;

import entidade.Voluntario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import persistencia.VoluntarioDAO;
import tablemodel.VoluntarioTableModel;

/**
 *
 * @author ATILLA
 */
public class AddVoluntario extends javax.swing.JDialog {

    private VoluntarioTableModel modelTabela;
    private static VoluntarioDAO vDAO;
    private Voluntario voluntario;
    
    public AddVoluntario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        vDAO = new VoluntarioDAO();
        
        try {
            modelTabela = new VoluntarioTableModel(vDAO.listar());
        } catch (Exception ex) {
            modelTabela = new VoluntarioTableModel();
            System.out.println(" \nErro ao listar voluntários ->>>>> \n"+ex.getMessage());
        }
        
        limpaTela();
        
        jTextFieldNomeVoluntario.requestFocus();
        jTableVoluntarios.setModel(modelTabela);
        jTableVoluntarios.getColumnModel().getColumn(1).setPreferredWidth(400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeVoluntario = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVoluntarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIdVoluntario = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonOrderNome = new javax.swing.JButton();
        jButtonOrderCodigo = new javax.swing.JButton();
        jButtonOrderTrocas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Voluntários");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setText("Nome do Voluntário:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 30, 140, 20);
        jPanel1.add(jTextFieldNomeVoluntario);
        jTextFieldNomeVoluntario.setBounds(220, 30, 200, 20);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(430, 30, 70, 23);

        jTableVoluntarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableVoluntarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableVoluntariosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVoluntarios);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 630, 280);

        jLabel2.setText("Voluntários Cadastrados:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 100, 130, 30);

        jLabel3.setText("Código:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 30, 60, 20);

        jTextFieldIdVoluntario.setEditable(false);
        jTextFieldIdVoluntario.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldIdVoluntario);
        jTextFieldIdVoluntario.setBounds(50, 30, 60, 20);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo);
        jButtonNovo.setBounds(570, 30, 70, 23);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(500, 30, 70, 23);

        jButtonOrderNome.setText("Nome");
        jButtonOrderNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderNomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOrderNome);
        jButtonOrderNome.setBounds(430, 100, 70, 23);

        jButtonOrderCodigo.setText("Código");
        jButtonOrderCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOrderCodigo);
        jButtonOrderCodigo.setBounds(500, 100, 70, 23);

        jButtonOrderTrocas.setText("Trocas");
        jButtonOrderTrocas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderTrocasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOrderTrocas);
        jButtonOrderTrocas.setBounds(570, 100, 70, 23);

        jLabel4.setText("Ordenar por:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 100, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-663)/2, (screenSize.height-456)/2, 663, 456);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        if(jTextFieldNomeVoluntario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o nome, neh...");
        } else {
            Integer id  = Integer.parseInt(jTextFieldIdVoluntario.getText());
            String nome = jTextFieldNomeVoluntario.getText().toUpperCase();
            
            voluntario.setId(id);
            voluntario.setNome(nome);
            modelTabela.salvar(voluntario);
            
            Main.atualizaVoluntarios();
            limpaTela();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        
        limpaTela();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTableVoluntariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVoluntariosMousePressed
        
        getLinhaDaTabelaSelecionada();
    }//GEN-LAST:event_jTableVoluntariosMousePressed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        int confirmacao = JOptionPane.showConfirmDialog(this, "Confirma exclusão do(a) "+ jTextFieldNomeVoluntario.getText() +"?", 
                    "Excluir Voluntário?", JOptionPane.YES_NO_OPTION);
        
        if(!jTextFieldIdVoluntario.getText().equals("0") && confirmacao == JOptionPane.YES_OPTION){
            try {
                Voluntario v = vDAO.getVoluntario(Integer.parseInt(jTextFieldIdVoluntario.getText()));
                modelTabela.excluir(v);
                Main.trocadores.remove(v);
                
                //Em caso de nenhum cadastro
                if(Main.trocadores.size() == 0){
                    Main.jTextFieldProximoTrocador.setText("");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao tentar excluir! Erro: "+ ex.getMessage());
            }
            limpaTela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione alguém, neh...");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonOrderNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderNomeActionPerformed

        modelTabela.ordenarPorNome();
    }//GEN-LAST:event_jButtonOrderNomeActionPerformed

    private void jButtonOrderCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderCodigoActionPerformed

        modelTabela.ordenarPorCodigo();
    }//GEN-LAST:event_jButtonOrderCodigoActionPerformed

    private void jButtonOrderTrocasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderTrocasActionPerformed

        modelTabela.ordenarPorQtdeDeTrocas();
    }//GEN-LAST:event_jButtonOrderTrocasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddVoluntario dialog = new AddVoluntario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonOrderCodigo;
    private javax.swing.JButton jButtonOrderNome;
    private javax.swing.JButton jButtonOrderTrocas;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVoluntarios;
    private javax.swing.JTextField jTextFieldIdVoluntario;
    private javax.swing.JTextField jTextFieldNomeVoluntario;
    // End of variables declaration//GEN-END:variables

    private void limpaTela(){
        voluntario = new Voluntario();
        
        jTextFieldIdVoluntario.setText("0");
        jTextFieldNomeVoluntario.setText("");
        jTextFieldNomeVoluntario.requestFocus();
    }

    private void getLinhaDaTabelaSelecionada() {
        int row = jTableVoluntarios.getSelectedRow();
        
        jTextFieldIdVoluntario.setText(String.valueOf(jTableVoluntarios.getValueAt(row, 0)));
        jTextFieldNomeVoluntario.setText(String.valueOf(jTableVoluntarios.getValueAt(row, 1)));
    }
}
